#!/usr/bin/env python3
"""Auto-generated by Ralph spec-executor."""

def add(a, b):
    return a + b


if __name__ == "__main__":
    import sys
    if len(sys.argv) > 1:
        try:
            result = add(*sys.argv[1:])
            print(result)
        except TypeError:
            print(f"Usage: python adder.py [args...]")
    else:
        print(f"add() = {add()}")
