#!/bin/bash
# Hacker News Daily Summary Automation
# Usage: ./hn-daily-automation.sh

echo "Hacker News Daily Summary Generator"
echo "====================================="
echo ""

# Run the Python script
python3 /home/opc/clawd/hn-daily-summary.py

echo ""
echo "Creating GitHub gist..."
echo ""

# Find the most recent summary file
LATEST_SUMMARY=$(ls -t /home/opc/clawd/hn-summary-*.md | head -1)

# Create GitHub gist
gh gist create "$LATEST_SUMMARY" --desc "Hacker News Daily Summary - Auto-generated by Clawd 🦞"

echo ""
echo "Done! Check your GitHub gists for the summary."
