#!/usr/bin/env python3
"""Auto-generated by Ralph spec-executor."""

def hello():
    return "Hello, World!"


if __name__ == "__main__":
    import sys
    if len(sys.argv) > 1:
        try:
            result = hello(*sys.argv[1:])
            print(result)
        except TypeError:
            print(f"Usage: python hello.py [args...]")
    else:
        print(f"hello() = {hello()}")
