#!/usr/bin/env python3
"""Auto-generated by Ralph spec-executor."""

import sys


def echo():
    """Main function."""
    if len(sys.argv) > 1:
        print(' '.join(sys.argv[1:]))


if __name__ == "__main__":
    echo()
