#!/usr/bin/env python3
"""
Research Session Helper - Auto-create memory files during research (v1.0.0)

Usage:
    python scripts/research.py start "AI Consciousness"
    python scripts/research.py add "New finding about awareness"
    python scripts/research.py source "https://arxiv.org/paper/1234"
    python scripts/research.py finish "Summary of research"
    python scripts/research.py status
"""

import argparse
import json
import os
import sys
from datetime import datetime
from typing import Dict, List, Optional


class ResearchSession:
    """Manage research sessions with auto memory creation."""
    
    def __init__(self, session_file: str = "/home/opc/clawd/.research-session.json"):
        self.session_file = session_file
        self.session = self._load_session()
    
    def _load_session(self) -> Dict:
        """Load current session or create new."""
        if os.path.exists(self.session_file):
            with open(self.session_file, "r") as f:
                return json.load(f)
        return {
            "active": False,
            "topic": None,
            "findings": [],
            "sources": [],
            "started_at": None,
        }
    
    def _save_session(self):
        """Save current session."""
        with open(self.session_file, "w") as f:
            json.dump(self.session, f, indent=2)
    
    def start(self, topic: str) -> Dict:
        """Start a new research session."""
        self.session = {
            "active": True,
            "topic": topic,
            "findings": [],
            "sources": [],
            "started_at": datetime.utcnow().isoformat(),
        }
        self._save_session()
        return self.session
    
    def add_finding(self, finding: str) -> Dict:
        """Add a finding to current session."""
        if not self.session.get("active"):
            print("Warning: No active research session")
            return self.session
        
        self.session["findings"].append({
            "timestamp": datetime.utcnow().isoformat(),
            "text": finding,
        })
        self._save_session()
        return self.session
    
    def add_source(self, source: str, description: str = None) -> Dict:
        """Add a source to current session."""
        if not self.session.get("active"):
            print("Warning: No active research session")
            return self.session
        
        self.session["sources"].append({
            "timestamp": datetime.utcnow().isoformat(),
            "url": source,
            "description": description,
        })
        self._save_session()
        return self.session
    
    def finish(self, summary: str = None) -> str:
        """Finish session and create memory file."""
        if not self.session.get("active"):
            print("Warning: No active research session")
            return ""
        
        topic = self.session["topic"]
        findings = self.session["findings"]
        sources = self.session["sources"]
        
        # Build memory content
        timestamp = datetime.utcnow().isoformat()
        started_at = self.session.get("started_at", timestamp)
        
        memory_content = f"""# {topic}

**Researched:** {started_at}
**Completed:** {timestamp}

## Summary

{summary or 'Research completed. See findings below.'}

## Key Findings

"""
        for i, finding in enumerate(findings, 1):
            finding_time = finding.get("timestamp", "")[:19]
            memory_content += f"### Finding {i} ({finding_time})\n\n{finding['text']}\n\n"
        
        memory_content += "## Sources\n\n"
        if sources:
            for source in sources:
                desc = source.get("description") or "Source"
                url = source.get("url", "")
                memory_content += f"- [{desc}]({url})\n"
        else:
            memory_content += "- No sources recorded\n"
        
        memory_content += "\n---\n*Auto-generated by research-session helper*\n"
        
        # Create memory file
        safe_name = topic.lower().replace(" ", "-").replace("/", "-")[:50]
        memory_file = f"/home/opc/clawd/memory/RESEARCH-{safe_name}.md"
        
        with open(memory_file, "w") as f:
            f.write(memory_content)
        
        # Also log via error-logger
        try:
            from scripts.error_logger import log_research_session
            log_research_session(topic, summary or "Research completed", [s.get("url") for s in sources])
        except ImportError:
            pass
        
        # Clear session
        self.session = {"active": False, "topic": None, "findings": [], "sources": [], "started_at": None}
        self._save_session()
        
        return memory_file
    
    def status(self) -> Dict:
        """Get current session status."""
        return self.session
    
    def cancel(self):
        """Cancel current session without saving."""
        self.session = {"active": False, "topic": None, "findings": [], "sources": [], "started_at": None}
        self._save_session()
        print("Session cancelled")


def main():
    parser = argparse.ArgumentParser(
        description="Research session helper - auto-create memory files",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
EXAMPLES:
    # Start a research session
    python scripts/research.py start "AI Consciousness"
    
    # Add findings as you discover them
    python scripts/research.py add "Found research paper on AI awareness"
    python scripts/research.py add "Discovered meta-cognition patterns"
    
    # Add sources
    python scripts/research.py add-source "https://arxiv.org/1234" "AI Awareness Paper"
    
    # Finish and create memory file
    python scripts/research.py finish "Research on AI consciousness complete"
    
    # Check status
    python scripts/research.py status

BEST PRACTICE:
    Start a research session before researching a topic.
    Add findings as you discover them.
    Finish the session when done to auto-create memory file.
"""
    )
    
    subparsers = parser.add_subparsers(dest="command", help="Commands")
    
    # Start
    parser_start = subparsers.add_parser("start", help="Start a research session")
    parser_start.add_argument("topic", help="Research topic")
    
    # Add finding
    parser_add = subparsers.add_parser("add", help="Add a finding")
    parser_add.add_argument("finding", help="The finding to add")
    
    # Add source
    parser_source = subparsers.add_parser("add-source", help="Add a source")
    parser_source.add_argument("url", help="Source URL")
    parser_source.add_argument("description", nargs="*", default=[], help="Source description (optional)")
    
    # Finish
    parser_finish = subparsers.add_parser("finish", help="Finish and create memory file")
    parser_finish.add_argument("summary", nargs="*", default=[], help="Research summary (optional)")
    
    # Status
    subparsers.add_parser("status", help="Show current session status")
    
    # Cancel
    subparsers.add_parser("cancel", help="Cancel current session")
    
    args = parser.parse_args()
    
    session = ResearchSession()
    
    if args.command == "start":
        result = session.start(args.topic)
        print(f"✅ Started research session: {args.topic}")
        print(f"   Findings: {len(result['findings'])}")
        print(f"   Sources: {len(result['sources'])}")
    
    elif args.command == "add":
        result = session.add_finding(args.finding)
        print(f"✅ Added finding (total: {len(result['findings'])})")
    
    elif args.command == "add-source":
        result = session.add_source(args.url, " ".join(args.description) if args.description else None)
        print(f"✅ Added source (total: {len(result['sources'])})")
    
    elif args.command == "finish":
        summary = " ".join(args.summary) if args.summary else None
        memory_file = session.finish(summary)
        if memory_file:
            print(f"✅ Created memory file: {memory_file}")
        else:
            print("❌ No active session")
    
    elif args.command == "status":
        status = session.status()
        if status.get("active"):
            print(f"Active session: {status['topic']}")
            print(f"Started: {status.get('started_at', 'Unknown')}")
            print(f"Findings: {len(status['findings'])}")
            print(f"Sources: {len(status['sources'])}")
        else:
            print("No active research session")
    
    elif args.command == "cancel":
        session.cancel()
        print("Session cancelled")
    
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
